service: ouj-wordnet-search
frameworkVersion: "3"
provider:
  name: aws
  profile: nzu
  region: ap-northeast-1
  runtime: nodejs18.x
  environment:
    # ${sls:stage} は ${opt:stage, self:provider.stage, "dev"} のショートカット
    REGION: ${aws:region}
    S3_BUCKET: ${self:service}-${sls:stage}-bucket
    TZ: Asia/Tokyo
    CX: ${self:custom.secrets.CX}
    KEY: ${self:custom.secrets.KEY}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
        - 's3:ListBucket'
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}'
        - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*'
  apiGateway:
    apiKeys:
      - get:
          - name: hk-wordnet-search-api
            value: ${self:custom.secrets.APP_API_KEY}
    usagePlan:
      - get:
          quota:
            limit: 1000 # API の呼び出しを行える最大回数
            period: DAY # DAY or WEEK or MONTH
          throttle:
            burstLimit: 100 # 同時に処理できる最大リクエスト数
            rateLimit: 20 # 1 秒あたりに処理できる API リクエスト数
functions:
  get:
    handler: handlers/search.search
    events:
      - http:
          path: search
          method: get
          cors: true
    memorySize: 2048 # メモリを2GBに設定
    timeout: 60
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        # AccessControl: PublicRead
        BucketName: ${self:provider.environment.S3_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Principal: '*'
              Action:
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:ListBucket'
              Resource:
                - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}'
                - 'arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*'
custom:
  secrets: ${file(secrets.yml)}
plugins:
  - serverless-offline